sudo: required
dist: trusty
language: cpp

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopenblas-dev liblapack-dev g++ libboost-all-dev
  - curl http://sourceforge.net/projects/arma/files/armadillo-9.800.2.tar.xz | tar xvz && cd armadillo*
  - cmake . && make && sudo make install && cd ..
  - sudo cp .travis/config.hpp /usr/include/armadillo_bits/config.hpp
  - cd $TRAVIS_BUILD_DIR && cd .. && git clone https://github.com/mlpack/mlpack.git --depth 1
  - cd mlpack && mkdir build && cd build && cmake .. && make -j2 && sudo make install
  
install:
  - cd $TRAVIS_BUILD_DIR && mkdir build && cd build && cmake ..
script:
  - make -j2

notifications:
  email:
    - mlpack-git@lists.mlpack.org
  irc:
    channels:
      - "chat.freenode.net#mlpack"
    on_success: change
on_failure: always
